env:
  ### cirrus config
  CIRRUS_CLONE_DEPTH: 1
  ### compiler options
  HOST:
  WRAPPER_CMD:
  # Specific warnings can be disabled with -Wno-error=foo.
  # -pedantic-errors is not equivalent to -Werror=pedantic and thus not implied by -Werror according to the GCC manual.
  WERROR_CFLAGS: -Werror -pedantic-errors
  MAKEFLAGS: -j4
  BUILD: check
  ### secp256k1 config
  ECMULTWINDOW: 15
  ECMULTGENKB: 22
  ASM: no
  WIDEMUL: auto
  WITH_VALGRIND: yes
  EXTRAFLAGS:
  ### secp256k1 modules
  EXPERIMENTAL: no
  ECDH: no
  RECOVERY: no
  EXTRAKEYS: no
  SCHNORRSIG: no
  MUSIG: no
  ELLSWIFT: no
  ### test options
  SECP256K1_TEST_ITERS: 64
  BENCH: yes
  SECP256K1_BENCH_ITERS: 2
  CTIMETESTS: yes
  SYMBOL_CHECK: yes
  VIRTUAL_ENV: /root/venv
  # Compile and run the tests
  EXAMPLES: yes

cat_logs_snippet: &CAT_LOGS
  always:
    cat_tests_log_script:
      - cat tests.log || true
    cat_noverify_tests_log_script:
      - cat noverify_tests.log || true
    cat_exhaustive_tests_log_script:
      - cat exhaustive_tests.log || true
    cat_ctime_tests_log_script:
      - cat ctime_tests.log || true
    cat_bench_log_script:
      - cat bench.log || true
    cat_config_log_script:
      - cat config.log || true
    cat_test_env_script:
      - cat test_env.log || true
    cat_ci_env_script:
      - env

linux_arm64_container_snippet: &LINUX_ARM64_CONTAINER
  env_script:
    - export PATH="$VIRTUAL_ENV/bin:$PATH"
    - env | tee /tmp/env
  build_script:
    - DOCKER_BUILDKIT=1 docker build --file "ci/linux-debian.Dockerfile" --tag="ci_secp256k1_arm"
    - docker image prune --force  # Cleanup stale layers
  test_script:
    - ./ci/cirrus.sh
  << : *CAT_LOGS

task:
  name: "arm64: macOS Monterey"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    # Cirrus gives us a fixed number of 4 virtual CPUs.
    MAKEFLAGS: -j5
  matrix:
    - env:
        CXX: g++-11
      # Homebrew's gcc for arm64 has no libubsan.
      matrix:
        - env:
            ENABLE_FIELDS: 28
        - env:
            BUILD: distcheck
    - env:
        CXX: clang++
      matrix:
        - env:
            ENABLE_FIELDS: 28
        - env:
            BUILD: distcheck
        - env:
            CXXFLAGS:  "-fsanitize=undefined -fno-omit-frame-pointer"
            LDFLAGS: "-fsanitize=undefined -fno-omit-frame-pointer"
            UBSAN_OPTIONS: "print_stacktrace=1:halt_on_error=1"
            BENCH: no
  brew_script:
    - brew update
    - brew install automake libtool gcc@11
  << : *MERGE_BASE
  test_script:
    - ./ci/cirrus.sh
  << : *CAT_LOGS

task:
  name: 'CentOS, depends, gui'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: small
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_centos.sh"

task:
  name: 'previous releases, depends DEBUG'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: small
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_previous_releases.sh"

task:
  name: 'TSan, depends, gui'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: medium
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_tsan.sh"

task:
  name: 'MSan, depends'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: small
  timeout_in: 300m  # Use longer timeout for the *rare* case where a full build (llvm + msan + depends + ...) needs to be done.
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_msan.sh"

task:
  name: 'fuzzer,address,undefined,integer, no depends'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: medium
  timeout_in: 240m  # larger timeout, due to the high CPU demand
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz.sh"

task:
  name: 'multiprocess, i686, DEBUG'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: medium
  env:
    FILE_ENV: "./ci/test/00_setup_env_i686_multiprocess.sh"

task:
  name: 'no wallet, libBGLkernel'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: small
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_nowallet_libBGLkernel.sh"

task:
  name: 'macOS-cross, gui, no tests'
  << : *GLOBAL_TASK_TEMPLATE
  persistent_worker:
    labels:
      type: arm64
  env:
    FILE_ENV: "./ci/test/00_setup_env_mac_cross.sh"
