blank_issues_enabled: true
contact_links:
  - name: Bitgesell Security Policy
    url: https://github.com/BitgesellOfficial/bitgesell/security/policy
    about: View security reporting guidance
  - name: Bitgesell Project
    url: https://github.com/BitgesellOfficial/bitgesell
    about: Bitgesell Core repository
