blank_issues_enabled: true
contact_links:
  - name: Bitgesell Security Policy
    url: https://github.com/BitgesellOfficial/bitgesell/blob/master/SECURITY.md
    about: View security policy
  - name: Bitgesell
    url: https://bitgesell.ca
    about: Bitgesell homepage
