blank_issues_enabled: true
contact_links:
  - name: BGL Core Security Policy
    url: https://github.com/BitgesellOfficial/bitgesell/blob/master/SECURITY.md
    about: View the project's security reporting policy
  - name: Bitgesell Website
    url: https://bitgesell.ca/
    about: Bitgesell project homepage
