name: Issue or feature request related to the GUI
description: Any report, issue or feature request related to the GUI
labels: [GUI]
body:
- type: checkboxes
  id: acknowledgement
  attributes:
    label: Issues, reports or feature requests related to the GUI should include enough detail for BGL Core maintainers to reproduce them
    description: Include screenshots, logs, and platform details when applicable.
    options:
      - label: I still think this issue should be opened here
        required: true
- type: textarea
  id: gui-request
  attributes:
    label: Report
  validations:
    required: true
