name: Issue or feature request related to the GUI
description: Any report, issue or feature request related to the GUI
labels: [GUI]
body:
- type: checkboxes
  id: acknowledgement
  attributes:
    label: I have checked existing Bitgesell GUI issues before opening this report.
    description: Please include screenshots or screen recordings when they help explain the GUI issue.
    options:
      - label: I still think this issue should be opened here
        required: true
- type: textarea
  id: gui-request
  attributes:
    label: Report
  validations:
    required: true
