
.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. BGL_qt test_BGL_qt
clean: FORCE
	$(MAKE) -C .. BGL_qt_clean test_BGL_qt_clean
check: FORCE
	$(MAKE) -C .. test_BGL_qt_check
BGL-qt BGL-qt.exe: FORCE
	 $(MAKE) -C .. BGL_qt
apk: FORCE
	$(MAKE) -C .. BGL_qt_apk